<?php
return [
    'BE' => [
        'debug' => false,
        'explicitADmode' => 'explicitAllow',
        'installToolPassword' => '$2y$12$rVqACYUj9SYdo3X.Vqjhl.QOY1ttJX8XD3Ow1CPkaYlBQ.mt9thEe',
        'loginSecurityLevel' => 'normal',
        'passwordHashing' => [
            'className' => 'TYPO3\\CMS\\Core\\Crypto\\PasswordHashing\\BcryptPasswordHash',
            'options' => [],
        ],
        'sessionTimeout' => 28800,
    ],
    'DB' => [
        'Connections' => [
            'Default' => [
                'charset' => 'utf8mb4',
                'dbname' => 'db',
                'driver' => 'mysqli',
                'host' => '127.0.0.1',
                'password' => 'root',
                'port' => '32792',
                'user' => 'root',
            ],
        ],
    ],
    'EXT' => [],
    'EXTCONF' => [
        'helhum-typo3-console' => [
            'initialUpgradeDone' => '10.4',
        ],
        'lang' => [
            'availableLanguages' => [
                'fr',
            ],
        ],
    ],
    'EXTENSIONS' => [
        'backend' => [
            'backendFavicon' => 'EXT:bza_main/Resources/Public/Images/Backend/backend-favicon.png',
            'backendLogo' => 'EXT:bza_main/Resources/Public/Images/Backend/backend-logo.jpg',
            'loginBackgroundImage' => 'EXT:bza_main/Resources/Public/Images/Backend/login-background.png',
            'loginFootnote' => 'Made with ♥ by Bertrand Zang',
            'loginHighlightColor' => '#6be6b0',
            'loginLogo' => 'EXT:bza_main/Resources/Public/Images/Backend/login-logo.jpg',
        ],
        'bootstrap_package' => [
            'disableCssProcessing' => '0',
            'disableFontLoader' => '0',
            'disableGoogleFontCaching' => '0',
            'disablePageTsBackendLayouts' => '0',
            'disablePageTsContentElements' => '0',
            'disablePageTsRTE' => '0',
            'disablePageTsTCEFORM' => '0',
            'disablePageTsTCEMAIN' => '0',
        ],
        'bza_main' => [
            'loginBackgroundRandom' => '0',
        ],
        'eventnews' => [
            'overrideAdministrationModuleLabel' => '0',
        ],
        'extensionmanager' => [
            'automaticInstallation' => '1',
            'offlineMode' => '0',
        ],
        'maps2' => [
            'allowMapTemplatePath' => 'EXT:maps2/Resources/Private/Templates/AllowMapForm.html',
            'defaultCountry' => '',
            'defaultLatitude' => '',
            'defaultLongitude' => '',
            'defaultMapProvider' => 'gm',
            'defaultRadius' => '250',
            'explicitAllowGoogleMaps' => '0',
            'explicitAllowGoogleMapsBySessionOnly' => '0',
            'explicitAllowMapProviderRequests' => '0',
            'explicitAllowMapProviderRequestsBySessionOnly' => '0',
            'fillColor' => '#FF0000',
            'fillOpacity' => '0.35',
            'googleMapsGeocodeApiKey' => 'AIzaSyAk0BmukOX_ubOx4_dz2Iz-ZyrlUF7qS-w',
            'googleMapsGeocodeUri' => 'https://maps.googleapis.com/maps/api/geocode/json?address=%s&key=%s',
            'googleMapsJavaScriptApiKey' => 'AIzaSyAk0BmukOX_ubOx4_dz2Iz-ZyrlUF7qS-w',
            'googleMapsLibrary' => 'https://maps.googleapis.com/maps/api/js?key=|&libraries=places',
            'infoWindowContentTemplatePath' => 'EXT:maps2/Resources/Private/Templates/InfoWindowContent.html',
            'mapProvider' => 'both',
            'markerIconAnchorPosX' => '13',
            'markerIconAnchorPosY' => '40',
            'markerIconHeight' => '40',
            'markerIconWidth' => '25',
            'openStreetMapGeocodeUri' => 'https://nominatim.openstreetmap.org/search/%s?format=json&addressdetails=1',
            'strokeColor' => '#FF0000',
            'strokeOpacity' => '0.8',
            'strokeWeight' => '2',
        ],
        'news' => [
            'advancedMediaPreview' => 'true',
            'archiveDate' => 'date',
            'categoryBeGroupTceFormsRestriction' => '0',
            'categoryRestriction' => '',
            'contentElementPreview' => '1',
            'contentElementRelation' => '1',
            'dateTimeNotRequired' => '0',
            'hidePageTreeForAdministrationModule' => '0',
            'manualSorting' => '0',
            'mediaPreview' => 'false',
            'prependAtCopy' => '1',
            'resourceFolderImporter' => '/news_import',
            'rteForTeaser' => '0',
            'showAdministrationModule' => '1',
            'showImporter' => '0',
            'slugBehaviour' => 'unique',
            'storageUidImporter' => '1',
            'tagPid' => '1',
        ],
        'scheduler' => [
            'maxLifetime' => '1440',
            'showSampleTasks' => '1',
        ],
        'sluggi' => [
            'last_segment_only' => '0',
            'pages_fields' => 'nav_title,title',
            'recursively' => '1',
            'redirect_code' => '307',
            'redirect_force_https' => '0',
            'redirect_keep_query_parameters' => '0',
            'redirect_lifetime' => '+1 month',
            'redirect_respect_query_parameters' => '0',
            'redirects' => '1',
            'slash_replacement' => '1',
            'synchronize' => '1',
            'use_transactions' => '1',
            'whitelist' => '',
        ],
        'staticfilecache' => [
            'backendDisplayMode' => 'both',
            'boostMode' => '0',
            'cacheTagsEnable' => '0',
            'clearCacheForAllDomains' => '1',
            'debugHeaders' => '0',
            'disableInDevelopment' => '0',
            'enableGeneratorBrotli' => '0',
            'enableGeneratorGzip' => '1',
            'enableGeneratorManifest' => '0',
            'enableGeneratorPlain' => '1',
            'hashUriInCache' => '0',
            'htaccessTemplateName' => 'EXT:staticfilecache/Resources/Private/Templates/Htaccess.html',
            'overrideCacheDirectory' => '',
            'rawurldecodeCacheFileName' => '0',
            'renameTablesToOtherPrefix' => '0',
            'sendCacheControlHeaderRedirectAfterCacheTimeout' => '0',
            'sendHttp2PushEnable' => '0',
            'sendHttp2PushFileExtensions' => 'css,js',
            'sendHttp2PushFileLimit' => '10',
            'sendHttp2PushLimitToArea' => '',
            'useFallbackMiddleware' => '1',
            'useReverseUriLengthInPriority' => '1',
            'validHtaccessHeaders' => 'Content-Type,Content-Language,Link,X-SFC-Tags',
        ],
        'vhs' => [
            'disableAssetHandling' => '0',
        ],
    ],
    'FE' => [
        'lifetime' => 604800,
        'loginSecurityLevel' => 'normal',
        'passwordHashing' => [
            'className' => 'TYPO3\\CMS\\Core\\Crypto\\PasswordHashing\\BcryptPasswordHash',
            'options' => [],
        ],
    ],
    'GFX' => [
        'jpg_quality' => 65,
        'processor' => 'GraphicsMagick',
        'processor_allowTemporaryMasksAsPng' => false,
        'processor_colorspace' => 'sRGB',
        'processor_effects' => false,
        'processor_enabled' => true,
        'processor_path' => '/usr/local/bin/',
        'processor_path_lzw' => '/usr/local/bin/',
    ],
    'MAIL' => [
        'defaultMailFromAddress' => '',
        'defaultMailFromName' => '',
        'transport' => 'smtp',
        'transport_smtp_encrypt' => false,
        'transport_smtp_password' => '',
        'transport_smtp_server' => '',
        'transport_smtp_username' => '',
    ],
    'SYS' => [
        'devIPmask' => '127.0.0.1,::1',
        'displayErrors' => false,
        'encryptionKey' => '211708d06a1411c35d33b8d165e1ff177412ce7768e5de977873afc742ac0fdba39d86a36781e600193b850dadf1acff',
        'errorHandlerErrors' => 32514,
        'exceptionalErrors' => 4352,
        'features' => [
            'felogin.extbase' => true,
            'fluidBasedPageModule' => true,
            'form.legacyUploadMimeTypes' => true,
            'rearrangedRedirectMiddlewares' => true,
            'redirects.hitCount' => false,
            'security.backend.enforceReferrer' => true,
            'security.frontend.keepSessionDataOnLogout' => false,
            'unifiedPageTranslationHandling' => true,
        ],
        'sitename' => 'Dummy TYPO3',
        'systemMaintainers' => [
            1,
        ],
        'trustedHostsPattern' => '(.*)',
    ],
];
