<?php

########################################################################
# Extension Manager/Repository config file for ext: "mrkeperson"
#
# Auto generated by Extension Builder 2011-11-08
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Manage Persons',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Jennifer Erlemann',
	'author_email' => 'mrke@zhaw.ch',
	'author_company' => 'ZHAW School of Management and Law',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'experimental',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'extbase' => '',
			'fluid' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>