<?php

namespace Zang\BzaMain\Tests\Unit;

use TYPO3\TestingFramework\Core\Unit\UnitTestCase;

/**
 * This is just a simple test to illustrate a unit test
 * Class DummyTest
 */
class DummyTest extends UnitTestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @test
     */
    public function someUselessTest() {
        $this->assertSame(true, true);
    }
}
